# Generated by Django 5.2.4 on 2025-07-11 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name': 'Tablica',
                'verbose_name_plural': 'Tablice',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kolumny')),
                ('column_type', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], max_length=20, verbose_name='Typ kolumny')),
                ('position', models.PositiveIntegerField(verbose_name='Pozycja')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='TrelloClone.board', verbose_name='Tablica')),
            ],
            options={
                'verbose_name': 'Kolumna',
                'verbose_name_plural': 'Kolumny',
                'ordering': ['position'],
                'unique_together': {('board', 'column_type')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('visibility', models.CharField(choices=[('public', 'Publiczny'), ('private', 'Prywatny')], default='private', max_length=10, verbose_name='Widoczność')),
                ('status', models.CharField(choices=[('active', 'Aktywny'), ('completed', 'Zakończony'), ('paused', 'Wstrzymany')], default='active', max_length=20, verbose_name='Status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('access_code', models.CharField(blank=True, max_length=8, unique=True, verbose_name='Kod dostępu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekty',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='TrelloClone.project', verbose_name='Projekt'),
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Treść komentarza')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Czy edytowany')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='TrelloClone.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Komentarz do projektu',
                'verbose_name_plural': 'Komentarze do projektów',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrelloClone.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Członkostwo w projekcie',
                'verbose_name_plural': 'Członkostwa w projektach',
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projects', through='TrelloClone.ProjectMembership', to=settings.AUTH_USER_MODEL, verbose_name='Członkowie'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł zadania')),
                ('description', models.TextField(blank=True, verbose_name='Opis zadania')),
                ('priority', models.CharField(choices=[('low', 'Niska'), ('medium', 'Średnia'), ('high', 'Wysoka')], default='medium', max_length=10, verbose_name='Priorytet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('position', models.PositiveIntegerField(verbose_name='Pozycja w kolumnie')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Termin wykonania')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Przypisane do')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='TrelloClone.column', verbose_name='Kolumna')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Utworzone przez')),
            ],
            options={
                'verbose_name': 'Zadanie',
                'verbose_name_plural': 'Zadania',
                'ordering': ['position'],
            },
        ),
    ]
